import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Card, Divider, Typography } from "antd";
import Link from "next/link";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}>
				<main className={styles.main}>
					<Image
						className={styles.logo}
						src="/next.svg"
						alt="Next.js logo"
						width={180}
						height={38}
						priority
					/>
					<ol>
						<li>
							Get started by editing <code>pages/index.tsx</code>.
						</li>
						<li>Save and see your changes instantly.</li>
					</ol>

					<Card>
						<Typography.Title level={4} style={{ color: "grey" }}>
							For Interns:
						</Typography.Title>
						<Divider style={{ marginTop: 5, marginBottom: 10 }} />
						<Typography.Paragraph>
							You can visit{" "}
							<code>
								<Link href="/playground">/playground</Link>
							</code>{" "}
							to view sample code, for your reference.
						</Typography.Paragraph>
						<Typography.Paragraph>
							<b style={{ color: "red", fontSize: "12px" }}>
								Note: Delete this page when you are done
							</b>
						</Typography.Paragraph>

						<div style={{ display: "flex", flexDirection: "column" }}>
							<Typography.Text strong>Useful Resources:</Typography.Text>
							<Typography.Paragraph>
								Below, you will find links to our commonly used packages during FE development:
							</Typography.Paragraph>
							<ol>
								<li>
									<Link
										href={
											"https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
										}
										target="_blank"
									>
										Next.js
									</Link>
								</li>
								<li>
									<Link href={"https://ant.design/components/overview/"} target="_blank">
										Ant Design v5
									</Link>
								</li>
								<li>
									<Link
										href={"https://zustand.docs.pmnd.rs/getting-started/introduction"}
										target="_blank"
									>
										Zustand (Our preferred state management library)
									</Link>
								</li>
								<li>
									<Link
										href={"https://day.js.org/docs/en/installation/installation"}
										target="_blank"
									>
										Day.js (Date and time library)
									</Link>
								</li>
								<li>
									<Link href={"https://fontawesome.com/icons"} target="_blank">
										FontAwesome Icons (Preferred Icon Library)
									</Link>
								</li>
							</ol>
						</div>
					</Card>

					<div className={styles.ctas}>
						<a
							className={styles.primary}
							href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
							target="_blank"
							rel="noopener noreferrer"
						>
							<Image
								className={styles.logo}
								src="/vercel.svg"
								alt="Vercel logomark"
								width={20}
								height={20}
							/>
							Deploy now
						</a>
						<a
							href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
							target="_blank"
							rel="noopener noreferrer"
							className={styles.secondary}
						>
							Read our docs
						</a>
					</div>
				</main>
				<footer className={styles.footer}>
					<a
						href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
						target="_blank"
						rel="noopener noreferrer"
					>
						<Image aria-hidden src="/file.svg" alt="File icon" width={16} height={16} />
						Learn
					</a>
					<a
						href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
						target="_blank"
						rel="noopener noreferrer"
					>
						<Image aria-hidden src="/window.svg" alt="Window icon" width={16} height={16} />
						Examples
					</a>
					<a
						href="https://nextjs.org?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
						target="_blank"
						rel="noopener noreferrer"
					>
						<Image aria-hidden src="/globe.svg" alt="Globe icon" width={16} height={16} />
						Go to nextjs.org →
					</a>
				</footer>
			</div>
		</>
	);
}
